services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sproute-api
    env_file: ".env"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sproute-web
    ports:
      - "5173:5173"
