services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sproute-api
    env_file: ".env"
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sproute-web
    environment:
      VITE_BACKEND_API: "http://localhost:3000"
    ports:
      - "5173:5173"
