name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          docker build \
            --build-arg FLASK_ENV=development \
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/sproute-api:latest ./backend
      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sproute-api:latest
      - name: Build frontend image
        run: |
          docker build \
            --build-arg VITE_BACKEND_API=http://localhost:3000 \
            -t ${{ secrets.DOCKER_USERNAME }}/sproute-web:latest ./web
      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sproute-web:latest
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use Google Container Registry
        run: gcloud auth configure-docker

      - name: Tag and Push Backend Image to Google Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/sproute-api:latest gcr.io/${{ secrets.GCP_PROJECT }}/sproute-api:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/sproute-api:latest
      - name: Tag and Push Frontend Image to Google Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/sproute-web:latest gcr.io/${{ secrets.GCP_PROJECT }}/sproute-web:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/sproute-web:latest
      - name: Deploy Backend to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service: sproute-api
          image: gcr.io/${{ secrets.GCP_PROJECT }}/sproute-api:latest
          region: us-central1

      - name: Deploy Frontend to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service: sproute-web
          image: gcr.io/${{ secrets.GCP_PROJECT }}/sproute-web:latest
          region: us-central1
